apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-ms-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-ms
  template:
    metadata:
      labels:
        app: authentication-ms
    spec:
      containers:
        - name: authentication-ms
          image: heyimjustalex/authentication-ms
          env:
            - name: WATCHFILES_FORCE_POLLING
              value: "true"
            - name: DB_HOSTNAME
              value: authentication-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: shop
            - name: API_AUTHENTICATION_PREFIX
              value: "/api"
            - name: JWT_TOKEN_ALG
              value: "HS256"
            - name: JWT_REFRESH_TOKEN_SECRET_KEY
              value: "fasfsafasfasfas"
            - name: JWT_ACCESS_TOKEN_SECRET_KEY
              value: "okokokokokokok"
            - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
              value: "10080"
            - name: JWT_REFRESH_TOKEN_EXPIRE_MINUTES
              value: "30"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-ms
spec:
  selector:
    app: authentication-ms
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
