apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-ms-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  template:
    metadata:
      labels:
        app: products-ms
    spec:
      containers:
        - name: products-ms
          image: heyimjustalex/products-ms
          env:
            - name: WATCHFILES_FORCE_POLLING
              value: "true"
            - name: DB_HOSTNAME
              value: orders-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: shop
            - name: API_ORDERS_PREFIX
              value: "/api"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: products-ms-svc
spec:
  selector:
    app: products-ms
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
