version: "3.9"
services:
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile.prod
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - network
networks:
  network:
