FROM node:20-alpine as builder
WORKDIR /app
COPY ./app/package.json ./
RUN npm install -g pnpm
RUN pnpm install
COPY ./app .
RUN pnpm run build

# FROM nginx:1.25.4-alpine-slim as production-stage
# COPY --from=build-stage /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf
# COPY default.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
