# Test version is with tests
version: "3.9"
services:
  ###  ----------------------------- API GATEWAY  -----------------------------
  api-gateway-ms:
    build:
      context: ./api-gateway-ms
      dockerfile: Dockerfile
    container_name: api-gateway-ms
    restart: always
    ports:
      - 8080:8000
    volumes:
      - ./api-gateway-ms/app/:/app:ro
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - JWT_TOKEN_ALG=HS256
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok
    networks:
      - network

  ### ----------------------------- AUTHENTICATION -----------------------------
  authentication-ms:
    build:
      context: ./authentication-ms
      # Prod version of Dockerfile
      dockerfile: Dockerfile.test
    container_name: authentication-ms
    restart: always
    depends_on:
      - authentication-db
    ports:
      - 8000:8000
    volumes:
      - ./authentication-ms/app/:/app:ro
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_HOSTNAME=authentication-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=27017
      - DB_NAME=shop
      # API ROUTES
      - API_AUTHENTICATION_PREFIX=/api
      # JWT CONF
      - JWT_TOKEN_ALG=HS256
      - JWT_REFRESH_TOKEN_SECRET_KEY=fasfsafasfasfas
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=30
    networks:
      - network

  ### ----------------------------- PRODUCTS -----------------------------
  products-ms:
    build:
      context: ./products-ms
      # Prod version of Dockerfile
      dockerfile: Dockerfile.test
    container_name: products-ms
    depends_on:
      - products-db
    ports:
      - 8001:8000
    volumes:
      - ./products-ms/app/:/app:ro
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_HOSTNAME=products-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=27017
      - DB_NAME=shop
      # API ROUTES
      - API_PRODUCT_PREFIX=/api

      # JWT CONF
      - JWT_TOKEN_ALG=HS256
      - JWT_REFRESH_TOKEN_SECRET_KEY=fasfsafasfasfas
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=30

    networks:
      - network
    restart: on-failure

  ### ----------------------------- ORDERS -----------------------------
  orders-ms:
    build:
      context: ./orders-ms
      # Prod version of Dockerfile
      dockerfile: Dockerfile.test
    container_name: orders-ms
    restart: always
    depends_on:
      - orders-db
    ports:
      - 8002:8000
    volumes:
      - ./orders-ms/app/:/app:ro
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_HOSTNAME=orders-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=27017
      - DB_NAME=shop
      # API ROUTES
      - API_ORDERS_PREFIX=/api
      # JWT CONF
      - JWT_TOKEN_ALG=HS256
      - JWT_REFRESH_TOKEN_SECRET_KEY=fasfsafasfasfas
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=30
    networks:
      - network

networks:
  network:
