# Dev version is without tests and live reload
version: "3.9"
services:
  publisher:
    container_name: publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    ports:
      - 8009:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
    networks:
      - network
    restart: on-failure
    volumes:
      - ./publisher/app/:/app:ro

  ###  ----------------------------- MESSAGE-BROKER  -----------------------------

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    networks:
      - network

  message-broker:
    image: confluentinc/cp-kafka:7.3.2
    hostname: message-broker
    container_name: message-broker
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    networks:
      - network
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://message-broker:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper
  ###  ----------------------------- API GATEWAY  -----------------------------
  api-gateway-ms:
    container_name: api-gateway-ms
    build:
      context: ./api-gateway-ms
      dockerfile: Dockerfile
    networks:
      - network
    restart: on-failure
    volumes:
      - ./api-gateway-ms/app/:/app:ro
    ports:
      - 8080:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - JWT_TOKEN_ALG=HS256
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok

  ### ----------------------------- AUTHENTICATION -----------------------------
  authentication-ms:
    container_name: authentication-ms
    depends_on:
      - authentication-db
    build:
      context: ./authentication-ms
      # Dev version of Dockerfile
      dockerfile: Dockerfile
      # Prod version of Dockerfile
      # dockerfile: Dockerfile.test
    volumes:
      - ./authentication-ms/app/:/app:ro
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_HOSTNAME=authentication-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=27017
      - DB_NAME=shop
      # API ROUTES
      - API_AUTHENTICATION_PREFIX=/api
      # JWT CONF
      - JWT_TOKEN_ALG=HS256
      - JWT_REFRESH_TOKEN_SECRET_KEY=fasfsafasfasfas
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=30
    networks:
      - network
    restart: on-failure

  authentication-db:
    image: mongo:7.0.7-rc2-jammy
    container_name: authentication-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: authentication
    volumes:
      # - users_db_data:/data/db
      - ./db/authentication-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - network

  adminpanel-authentication-db:
    image: mongo-express:1-20-alpine3.19
    container_name: adminpanel-authentication-db
    depends_on:
      - authentication-db
    restart: always
    environment:
      # this does not seem to work to modify connection server
      - ME_CONFIG_MONGODB_SERVER=authentication-db
      # but this does for some reason
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@authentication-db:27017/
      # db connection username and password because one from link above don't work
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
    # to login to panel use: admin/pass
    networks:
      - network

  ### ----------------------------- PRODUCTS -----------------------------
  products-ms:
    container_name: products-ms
    depends_on:
      - products-db
    build:
      context: ./products-ms
      # Dev version of Dockerfile
      dockerfile: Dockerfile
      # Prod version of Dockerfile
      # dockerfile: Dockerfile.test
    volumes:
      - ./products-ms/app/:/app:ro
    ports:
      - 8001:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_HOSTNAME=products-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=27017
      - DB_NAME=shop
      # API ROUTES
      - API_PRODUCT_PREFIX=/api

      # JWT CONF
      - JWT_TOKEN_ALG=HS256
      - JWT_REFRESH_TOKEN_SECRET_KEY=fasfsafasfasfas
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=30

    networks:
      - network
    restart: on-failure

  products-db:
    image: mongo:7.0.7-rc2-jammy
    container_name: products-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: products
    volumes:
      # - users_db_data:/data/db
      - ./db/products-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - network

  adminpanel-products-db:
    image: mongo-express:1-20-alpine3.19
    container_name: adminpanel-products-db
    depends_on:
      - products-db
    restart: always
    ports:
      - "8082:8081"
    environment:
      # this does not seem to work to modify connection server
      - ME_CONFIG_MONGODB_SERVER=products-db
      # but this does for some reason
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@products-db:27017/
      # db connection username and password because one from link above don't work
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
    # to login to panel use: admin/pass
    networks:
      - network
  ### ----------------------------- ORDERS -----------------------------
  orders-ms:
    container_name: orders-ms
    depends_on:
      - orders-db
    build:
      context: ./orders-ms
      # Dev version of Dockerfile
      dockerfile: Dockerfile
      # Prod version of Dockerfile
      # dockerfile: Dockerfile.test
    volumes:
      - ./orders-ms/app/:/app:ro
    ports:
      - 8002:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_HOSTNAME=orders-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=27017
      - DB_NAME=shop
      # API ROUTES
      - API_ORDERS_PREFIX=/api
      # JWT CONF
      - JWT_TOKEN_ALG=HS256
      - JWT_REFRESH_TOKEN_SECRET_KEY=fasfsafasfasfas
      - JWT_ACCESS_TOKEN_SECRET_KEY=okokokokokokok
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=30

    networks:
      - network
    restart: on-failure

  orders-db:
    image: mongo:7.0.7-rc2-jammy
    container_name: orders-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: orders
    volumes:
      # - orders_db_data:/data/db
      - ./db/orders-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - network

  adminpanel-orders-db:
    image: mongo-express:1-20-alpine3.19
    container_name: adminpanel-orders-db
    depends_on:
      - orders-db
    restart: always
    ports:
      - "8083:8081"
    environment:
      # this does not seem to work to modify connection server
      - ME_CONFIG_MONGODB_SERVER=orders-db
      # but this does for some reason
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@orders-db:27017/
      # db connection username and password because one from link above don't work
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
    # to login to panel use: admin/pass
    networks:
      - network

volumes:
  users_db_data:
    name: users_db_data

networks:
  network:
