services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - network

networks:
  network:
