services:
  nginx:
    image: nginx:1.25.4-alpine-slim
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - network

networks:
  network:
