### ----------------------------- ORDERS -----------------------------
version: "3.9"
services:
  orders-ms:
    build:
      context: ./orders-ms
      # Dev version of Dockerfile
      dockerfile: Dockerfile
      # Prod version of Dockerfile
      # dockerfile: Dockerfile.test
    container_name: orders-ms
    restart: always
    ports:
      - 8002:8000
    # depends_on:
    # - message-broker
    # - orders-db
    volumes:
      - ./orders-ms/app/:/app:ro
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_HOSTNAME=orders-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=27017
      - DB_NAME=shop
      # API ROUTES
      - API_ORDERS_PREFIX=/api

    networks:
      - network
networks:
  network:
