apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls-secret
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZCekNDQSsrZ0F3SUJBZ0lTQkN6aVc1cFR0NkwzbiszdFZ2WXAyRzhETUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlOREEwTWpNd09UTTVNREZhRncweU5EQTNNakl3T1RNNU1EQmFNQ2d4SmpBa0JnTlZCQU1UCkhXTnNiM1ZrWTI5dGNIVjBhVzVuZEdWamFHNXZiRzluYVdWekxuQnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUFpZGFpL0FEZlJrMmdLWVhBaGtBN2pPVGxYUkJYbXAxczBlWjFINXprdTZqeQpJTUNndHBKbkN3L3NtMXdmbEFBU2wreHBoa0lhbTFKcGZjcjZJd25qWDVlSFZ2aHpWWitxUWx6YzhpUk0vNE9mCmFXcnJHMW04dUI1UUdJSHYrQkI2SG56Y24zcmJmcGpSK2ZDc2lOblpjMlRTK3dnMlU2Ty9ZVXBxVXFSYXVSdmUKNWhpT3lsQ1BqOEtYR2orMStCNURzVG42cjR3QkhBbW5RT1h0NU1udGN4Z01KVGtVNlUwcjVVYWt5SG9DbExjRwpHRHNLM0ZWMVpkY3BGWnd2M2o2TlVOVmdCUUFKK2hMYmNHNXgrMzBHMUZONGN2NUNsOGpIeXdPQ0k0UVI0My9ECmxYazUxTEowbzNjTXMvQ1NZUG9uVE5nMnBOSFBQSnVIY3lpSlFyNnhZd0lEQVFBQm80SUNIekNDQWhzd0RnWUQKVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVgpIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlM4VTc3OXZYbkI2NG14b2VLVlpUTkdSdHVmQWpBZkJnTlZIU01FCkdEQVdnQlFVTHJNWHQxaFd5NjVRQ1VEbUg2K2RpeFRDeGpCVkJnZ3JCZ0VGQlFjQkFRUkpNRWN3SVFZSUt3WUIKQlFVSE1BR0dGV2gwZEhBNkx5OXlNeTV2TG14bGJtTnlMbTl5WnpBaUJnZ3JCZ0VGQlFjd0FvWVdhSFIwY0RvdgpMM0l6TG1rdWJHVnVZM0l1YjNKbkx6QW9CZ05WSFJFRUlUQWZnaDFqYkc5MVpHTnZiWEIxZEdsdVozUmxZMmh1CmIyeHZaMmxsY3k1d2JEQVRCZ05WSFNBRUREQUtNQWdHQm1lQkRBRUNBVENDQVFRR0Npc0dBUVFCMW5rQ0JBSUUKZ2ZVRWdmSUE4QUIxQUQ4WFMwL1hJa2RZbEIxbEhJUytEUkx0a0RkL0g0VnE2OEcvS0lYcytHUnVBQUFCandxSgpuSWtBQUFRREFFWXdSQUlnTTNEWStnWGRKN2EySUFndng3RzRSS1JDNDJrTVJxbUZ1VUxsMnVYSkYvSUNJQzhDCjFDQm9iOWhRNHpyd3BhbGZ5V0ZGdTA3K0F1WmZheVVQa09NcDg5Uk5BSGNBU0xEamE5cW1SelFQNVdvQytwMHcKNnh4U0FjdFczU3lCMmJ1L3F6blloSE1BQUFHUENvbWNqd0FBQkFNQVNEQkdBaUVBK3VYZHhtM2hWUXJmR3I0ZQpydTdjM25aS05QbDA0K2UzS0Z5aHRLLzJOOGdDSVFEMmF0UWxnRTAvMkZlTDV1QVZvNkwxbThaVTlnVDJscGxJClVoWmNsQUxhRmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVV4ejNzR0haQ0txeStUYmd5aTZpZ0Jjc2VRam8KT25yc3BhNW5ReDhBTnFsS3Q2Q2NaK2xxc1dDa2lvYzN4L0E5QWgzQ3VCbnQ3ZXFndit4RHdDZXNNb1JwMjM1UQpKZSswL1V5M2VrSWV6RkVxZkg3ZEx5YS9yVUtsQnk1dHFYMmw2czBleGozWERtTHcybjhWaGJ4WWY5RVZxNGVzCjZmYmJ2cjFzc1YreWt1SkxEK0JCRkJEWkZVbUhvWnNOVk0weVd6NytLRlZpUlJ6N0IybnYyK052aWFKT0RvbnUKWTJLUU04OTFKejZjQVRkWVMyWmtGclVzZFNtSUtCbnMvcklvQU54OWpyUytxajFKbThWeGRaS2l5OVdMT2t1YwpEL09nenRrb0tHdlRxZkQ4dmVnN21Ub3oxK1UyWWdrN1orNWJ0TlFCcFBtSkFkeGJCd2NNSDRwdHhnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRkZqQ0NBdjZnQXdJQkFnSVJBSkVyQ0VyUERCaW5VL2JXTGlXblgxb3dEUVlKS29aSWh2Y05BUUVMQlFBdwpUekVMTUFrR0ExVUVCaE1DVlZNeEtUQW5CZ05WQkFvVElFbHVkR1Z5Ym1WMElGTmxZM1Z5YVhSNUlGSmxjMlZoCmNtTm9JRWR5YjNWd01SVXdFd1lEVlFRREV3eEpVMUpISUZKdmIzUWdXREV3SGhjTk1qQXdPVEEwTURBd01EQXcKV2hjTk1qVXdPVEUxTVRZd01EQXdXakF5TVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5UR1YwSjNNZwpSVzVqY25sd2RERUxNQWtHQTFVRUF4TUNVak13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM3QWhVb3pQYWdsTk1QRXV5TlZaTEQrSUx4bWFaNlFvaW5YU2FxdFN1NXhVeXhyNDVyK1hYSW85Y1AKUjVRVVZUVlhqSjZvb2prWjlZSThRcWxPYnZVN3d5N2JqY0N3WFBOWk9PZnR6Mm53V2dzYnZzQ1VKQ1dIK2pkeApzeFBuSEt6aG0rL2I1RHRGVWtXV3FjRlR6alRJVXU2MXJ1MlAzbUJ3NHFWVXE3WnREcGVsUURScks5TzhadXRtCk5IejZhNHVQVnltWitEQVhYYnB5Yi91QnhhM1NobGc5RjhmbkNidnhLL2VHM01IYWNWM1VSdVBNclNYQmlMeGcKWjNWbXMvRVk5NkpjNWxQL09vaTJSNlgvRXhqcW1BbDNQNTFUK2M4QjVmV21jQmNVcjJPay81bXprNTNjVTZjRwova2lGSGFGcHJpVjF1eFBNVWdQMTdWR2hpOXNWQWdNQkFBR2pnZ0VJTUlJQkJEQU9CZ05WSFE4QkFmOEVCQU1DCkFZWXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0lHQ0NzR0FRVUZCd01CTUJJR0ExVWRFd0VCL3dRSU1BWUIKQWY4Q0FRQXdIUVlEVlIwT0JCWUVGQlF1c3hlM1dGYkxybEFKUU9ZZnI1MkxGTUxHTUI4R0ExVWRJd1FZTUJhQQpGSG0wV2VaN3R1WGtBWE9BQ0lqSUdsajI2WnR1TURJR0NDc0dBUVVGQndFQkJDWXdKREFpQmdnckJnRUZCUWN3CkFvWVdhSFIwY0RvdkwzZ3hMbWt1YkdWdVkzSXViM0puTHpBbkJnTlZIUjhFSURBZU1CeWdHcUFZaGhab2RIUncKT2k4dmVERXVZeTVzWlc1amNpNXZjbWN2TUNJR0ExVWRJQVFiTUJrd0NBWUdaNEVNQVFJQk1BMEdDeXNHQVFRQgpndDhUQVFFQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ0Z5azVIUHFQM2hVU0Z2TlZuZUxLWVk2MTFUUjZXClBUTmxjbFF0Z2FEcXcrMzRJTDlmekxkd0FMZHVPL1plbE43a0lKK203NHV5QStlaXRSWThrYzYwN1RrQzUzd2wKaWtmbVpXNC9SdlRaOE02VUsrNVV6aEs4akNkTHVNR1lMNkt2elhHUlNnaTN5TGdqZXdRdENQa0lWejZEMlFRegpDa2NoZUFtQ0o4TXF5SnU1emx6eVpNakF2bm5BVDQ1dFJBeGVrcnN1OTRzUTRlZ2RSQ25iV1NEdFk3a2grQkltCmxKTlhvQjFsQk1FS0lxNFFEVU9Yb1JnZmZ1RGdoamUxV3JHOU1MK0hiaXNxL3lGT0d3WEQ5UmlYOEY2c3c2VzQKYXZBdXZEc3p1ZTVMM3N6ODVLK0VDNFkvd0ZWRE52Wm80VFlYYW82WjBmK2xRS2MwdDhEUVl6azFPWFZ1OHJwMgp5Sk1DNmFsTGJCZk9EQUxadllIN243ZG8xQVpsczRJOWQxUDRqbmtEclFveEIzVXFROWhWbDNMRUtRNzN4RjFPCnlLNUdoRERYOG9WZkdLRjV1K2RlY0lzSDRZYVR3N21QM0dGeEpTcXYzKzBsVUZKb2k1TGM1ZGExNDlwOTBJZHMKaENFeHJvTDErN21yeUlrWFBlRk01VGdPOXIwcnZaYUJGT3ZWMnowZ3AzNVowK0w0V1BsYnVFak4vbHhQRmluKwpIbFVqcjhnUnNJM3FmSk9RRnkvOXJLSUpSMFkvOE9td3QvOG9UV2d5MW1kZUhtbWprN2oxbllzdkM5SlNRNlp2Ck1sZGxUVEtCM3poVGhWMStYV1lwNnJqZDVKVzF6YlZXRWtMTnhFN0dKVGhFVUczc3pnQlZHUDdwU1dUVVRzcVgKbkxSYndIT29xN2hId2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ0oxcUw4QU45R1RhQXAKaGNDR1FEdU01T1ZkRUZlYW5XelI1blVmbk9TN3FQSWd3S0Mya21jTEQreWJYQitVQUJLWDdHbUdRaHFiVW1sOQp5dm9qQ2VOZmw0ZFcrSE5WbjZwQ1hOenlKRXovZzU5cGF1c2JXYnk0SGxBWWdlLzRFSG9lZk55ZmV0dCttTkg1CjhLeUkyZGx6Wk5MN0NEWlRvNzloU21wU3BGcTVHOTdtR0k3S1VJK1B3cGNhUDdYNEhrT3hPZnF2akFFY0NhZEEKNWUza3llMXpHQXdsT1JUcFRTdmxScVRJZWdLVXR3WVlPd3JjVlhWbDF5a1ZuQy9lUG8xUTFXQUZBQW42RXR0dwpibkg3ZlFiVVUzaHkva0tYeU1mTEE0SWpoQkhqZjhPVmVUblVzblNqZHd5ejhKSmcraWRNMkRhazBjODhtNGR6CktJbEN2ckZqQWdNQkFBRUNnZ0VBR2I3V2FIMTlOck52RS9KZ21ITE03SzhnVERhdU5qbnJSblZtTVFac0RzVXEKbklWK1B6dXZOWGkrOS9ISUVDdkhUVXNpRnFxb0w1VEFFWGZsS3NCQkVPekxvYW44V09UZXQxQ0RFRk5KY254UwpQUzEwUm9LSFpsaDdHMmpCdXJMUkxIcWo5c0hLMTZXUnFyNlNhMmxOWFdsYW92clFzdVNsN1hVcDBNL1VCamp4ClI5M21oVlFmK0k4QkFyUFREN0s4WVZsaVBQQkRzRFZBc25mQTdLNkRFQk5BczBXVmEyN1JSNElpeEZOTkhsRG4KUzh6ZWNCMTQwcWVDMmM5b1RqQkV3NTFVY3U5NWExNk5yN2prVlFyQVZzTjYxQ3FSZmhjK1paVlJiN2I2c2pLaQp6Tmc0N0lyV013ZkF3UFJkaE8wVXRiL1FSbFhMMmFhUlFmeDM2YlBPeVFLQmdRQzdkaWZBVFVsK0o5ODNNRkRMCmhGSEdtSFdlUXVpUDhpSDdTSU9LNkNNK2NKTXlJYlJTMnR2QTVqYlZMYzhJc1pGUllOSFYwcTNMZnV4VldrUlgKQ1cwY3ArdktmL3VNOVhRT1RBbkNBbkx6eWdBZmk3aklBbEtvdGZLMEpqYUtUVm5oUzRKZ1IrRFB4MkVRMTJVRQp5Y3oxd09mYnBsa05DeUFlaVdvekNiTkF2d0tCZ1FDOE8rZU9CMXNTRDQwQyt5dFc0SUt2RSt1S1VvY3lLYkp6CkIzUVNOZWNVd3dUK0Eva0ZpeG8zSlRoTEc4NWszZkI5V0JzQjNQY05UT2VUTDhNaFF6cDlHdzR1V1Q5ZmN5c3cKK2dMRkkzTW41cXdSODYrRU8yU3JaTFdrbjBuc2lBdWpSRnZvWjBqVm5JZ0Ivc2NhdFNIOTJqbzRocGhWZEtCQwowWDFoMDM3VVhRS0JnR0c0OG5mNDBqc0ZwZ01yR0xNL1F6SDRBRGlFUUovcFpYV05FNld4NWMyQytmakVRVENBCkR0YThMQkZ0VStRQVRQVFRPQS96Ujg0eFdCb1dlRkczQkQ1UCswY1ErSjAreDBVOHRrbUE1VlBaRmI5Y0l2T0EKNG40NGUxRVdLcEJtU2xoNytIY2dnVDFQZm5ZOUV0Z3dLcnhoMTN4VmQwNnBZaEVKS1dkNXd3d1pBb0dBYXM0Swp5eG45WUxnV0tQVGZXSUkzWktRRzZBdC96c1MrRG1yU1AycjZYVnR5djdiOVcxbmNYQ0h3V1IzRDlKUEIyejFjCnhhZmRQbHkrb1ZOZWdzY2tyc3ZsTmdOSjVCenpDdTB4R1M3T0xudkNjc1UwZC9GRFk4VFhGRHVWdEhKVk9DU1gKaWJ6aEpPT1dnSnRSMmlPZ3orczlVY2w5TWkva3AwVTZ3WUZCMjdrQ2dZQlRPV2JtSlFxMm5ycVgzamhmRkFtRwpiVmQ4R2RUYjR5R3lJZjNpY3c2RzAyTlg0YTZFR1ZPbmJJM0l0S2lYY29NODgrUGM1OCt6UXFJTUppNmVkU28rCkhyZ2ZhZkNETVRISmJKUkE1WEs1ZGZqL01TeUVuNExuYTgyZGlscUNxUlRoRm1OcjRMVUc1dWIraUYzTnZ3YmYKUHBCNTMwZWRMeEZuN2NUTHlGdE0zdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - cloudcomputingtechnologies.pl
      secretName: nginx-tls-secret
  rules:
    - host: cloudcomputingtechnologies.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-ms-svc
                port:
                  number: 8000
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
#   namespace: default
# data:
#   default.conf: |
#     server {
#         listen 80;
#         server_name cloudcomputingtechnologies.pl;

#         location / {
#             root /usr/share/nginx/html;
#             index index.html;
#         }
#     }

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   namespace: default
# spec:
#   selector:
#     app: nginx
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx
#           volumeMounts:
#             - name: nginx-config
#               mountPath: /etc/nginx/conf.d/default.conf
#               subPath: default.conf
#       volumes:
#         - name: nginx-config
#           configMap:
#             name: nginx-config
