version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  test-authentication-ms:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          app-dir: backend/authentication-ms
          pip-dependency-file: requirements.dev
          pkg-manager: pip
      - run:
          name: Run tests
          command: cd backend/authentication-ms && python -m pytest --junit-xml ./app/test.xml
      - store_test_results:
          path: backend/authentication-ms/app/test.xml

workflows:
  main:
    jobs:
      - test-authentication-ms
