version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          app-dir: backend/authentication-ms
          pip-dependency-file: requirements.dev
          pkg-manager: pip
      - run:
          name: Run tests
          command: cd backend/authentication-ms && python -m pytest
      - store_artifacts:
          path: /app/test.xml
          destination: test-result

workflows:
  main:
    jobs:
      - build
