version: 2.1
orbs:
  python: circleci/python@2.1.1

executors:
  docker-publisher:
    docker:
      - image: circleci/golang:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  test-authentication-ms:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          app-dir: backend/authentication-ms
          pip-dependency-file: requirements.dev
          pkg-manager: pip
      - run:
          name: Run tests
          command: cd backend/authentication-ms && python -m pytest --junit-xml ./app/test.xml
      - store_test_results:
          path: backend/authentication-ms/app/test.xml


  build-and-publish-authentication-ms-image:
      executor: docker-publisher
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
                echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker build -t heyimjustalex/authentication-ms -f ./backend/authentication-ms/Dockerfile.prod ./backend/authentication-ms/
                docker push heyimjustalex/authentication-ms:latest


  test-products-ms:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          app-dir: backend/products-ms
          pip-dependency-file: requirements.dev
          pkg-manager: pip
      - run:
          name: Run tests
          command: cd backend/products-ms && python -m pytest --junit-xml ./app/test.xml
      - store_test_results:
          path: backend/products-ms/app/test.xml  

  build-and-publish-products-ms-image:
      executor: docker-publisher
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
                echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker build -t heyimjustalex/products-ms -f ./backend/products-ms/Dockerfile.prod ./backend/products-ms/
                docker push heyimjustalex/products-ms:latest

  test-orders-ms:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          app-dir: backend/orders-ms
          pip-dependency-file: requirements.dev
          pkg-manager: pip
      - run:
          name: Run tests
          command: cd backend/orders-ms && python -m pytest --junit-xml ./app/test.xml
      - store_test_results:
          path: backend/orders-ms/app/test.xml   

  deploy-orders-ms-gcp:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          app-dir: backend/orders-ms
          pip-dependency-file: requirements.dev
          pkg-manager: pip
      - run:
          name: Run tests
          command: cd backend/orders-ms && python -m pytest --junit-xml ./app/test.xml
      - store_test_results:
          path: backend/orders-ms/app/test.xml                        

  build-and-publish-orders-ms-image:
      executor: docker-publisher
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
                echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker build -t heyimjustalex/orders-ms -f ./backend/orders-ms/Dockerfile.prod ./backend/orders-ms/
                docker push heyimjustalex/orders-ms:latest

  build-and-publish-frontend:
      executor: docker-publisher
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
                echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                ls
                pwd
                docker build --build-arg="VITE_APP_BACKEND_ADDRESS=https://cloudcomputingtechnologies.pl/api" -t heyimjustalex/frontend -f ./frontend/app/Dockerfile.prod ./frontend/app
                docker build --build-arg="VITE_APP_BACKEND_ADDRESS=https://localhost/api" -t heyimjustalex/frontend:minikube -f ./frontend/app/Dockerfile.prod ./frontend/app
                docker push heyimjustalex/frontend:latest
                docker push heyimjustalex/frontend:minikube

workflows:
  authentication-ms-deploy:
    jobs:
      - test-authentication-ms
      - build-and-publish-authentication-ms-image:
          requires:
            - test-authentication-ms

  products-ms-deploy:
    jobs:
      - test-products-ms
      - build-and-publish-products-ms-image:
          requires:
            - test-products-ms

  orders-ms-deploy:
    jobs:
      - test-orders-ms
      - build-and-publish-orders-ms-image:
          requires:
            - test-orders-ms

  frontend-deploy:
    jobs:
      - build-and-publish-frontend

      


    
