# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing with Python, read the docs:
# https://circleci.com/docs/language-python/ for more details
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Python orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@3.11

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
# jobs:
#   test-authentication-ms:
#     # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
#     # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
#     docker:
#       # Specify the version you desire here
#       # See:https://circleci.com/developer/images/image/cimg/python
#       - image: cimg/python:3.11
#     steps:
#       - checkout
#       - python/install-packages:
#           pkg-manager: pip
#           app-dir: ~/e-commerces-microservices/backend/authentication-ms
#           pip-dependency-file: requirements.dev
#       - run:
#           name: Where
#           command: pwd
#       - run:
#           name: Where2
#           command: ls

#       - run:
#           name: Run tests
#           command: python -m pytest
jobs:
  test-authentication-ms: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-microservices:
    jobs:
      - test-authentication-ms