FROM python:3.12-slim as tester
WORKDIR /app
COPY requirements.txt /app
RUN apt-get update && \
 apt-get install -y python3-pip && \
 pip3 install pytest && \
 pip3 install --no-cache-dir -r requirements.txt
COPY . /app/
RUN [ "python3", "-m", "pytest", "--junit-xml", "/app/test_results.xml"]

FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app/
COPY --from=tester /app/test_results.xml .
COPY requirements.txt /app/
RUN apt-get update && \
 apt-get install -y python3-pip && \
 pip3 install pytest && \
 pip3 install --no-cache-dir -r requirements.txt
 # Difference, we don't want test folder no more
COPY ./app /app/
EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000","--reload"]
