apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
        - name: message-broker
          image: confluentinc/cp-kafka:7.3.2
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 19092
              name: kafka-internal
            - containerPort: 9999
              name: jmx
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://message-broker-svc:29092,EXTERNAL://message-broker-svc:19092,DOCKER://message-broker-svc:29093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LOG4J_LOGGERS
              value: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "9999"
            - name: KAFKA_JMX_HOSTNAME
              value: "${DOCKER_HOST_IP:-127.0.0.1}"
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              value: "kafka.security.authorizer.AclAuthorizer"
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              value: "true"

          resources:
            limits:
              cpu: "400m"
              memory: "500Mi"
            requests:
              cpu: "400m"
              memory: "500Mi"
      tolerations:
        - key: instance_type
          value: spot
          effect: NoSchedule
          operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops

---
apiVersion: v1
kind: Service
metadata:
  name: message-broker-svc
spec:
  selector:
    app: message-broker
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: kafka-internal
      port: 29092
      targetPort: 29092
    - name: jmx
      port: 9999
      targetPort: 9999
