apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-ms-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-ms
  template:
    metadata:
      labels:
        app: products-ms
    spec:
      restartPolicy: Always
      containers:
        - name: products-ms
          image: heyimjustalex/products-ms
          imagePullPolicy: "Always"
          env:
            - name: DB_HOSTNAME
              value: "products-db-svc.default"
            - name: WATCHFILES_FORCE_POLLING
              value: "true"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "message-broker-svc:29092"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: shop
            - name: API_products_PREFIX
              value: "/api"
          livenessProbe:
            httpGet:
              path: /api/products_health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "180m"
              memory: "120Mi"
            requests:
              cpu: "180m"
              memory: "120Mi"
      tolerations:
        - key: instance_type
          value: spot
          effect: NoSchedule
          operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - devops
---
apiVersion: v1
kind: Service
metadata:
  name: products-ms-svc
spec:
  selector:
    app: products-ms
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
